# Generated by Django 5.2.8 on 2025-12-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0005_refundrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventoryApp.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pendingcart",
            unique_together={("staff",)},
        ),
    ]
