# Generated by Django 5.2.8 on 2026-01-07 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0008_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="original_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="refund_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund_requests",
                to="inventoryApp.sale",
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="sale_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventoryApp.saleitem",
            ),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard Update"),
                            ("debtors", "New Debtors"),
                            ("refunds", "New Refund Requests"),
                            ("sales", "New Sales"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_id", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="user_notifi_user_id_ea6762_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type", "is_read"],
                        name="user_notifi_user_id_64a763_idx",
                    ),
                ],
            },
        ),
    ]
