# Generated by Django 5.2.8 on 2026-01-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0009_refundrequest_original_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("transfer", "Bank Transfer"),
                    ("refund", "Refund Adjustment"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="inventoryApp.sale",
            ),
        ),
    ]
